version: "3.1"
services:
  propiedades_db:
    container_name: propiedades_db
    build:
      context: ./bd/
    env_file: ./bd/mysql/.env.mysql
    ports:
      - "3306:3306"
    volumes:
      - ./bd/mysql/data:/var/lib/mysql
networks:
  default:
    external:
      name: propiedades-network
